name: gubot
skip_insecure: false # skip ssl verification (scripts and adapters have to use the httpclient created by gubot)
tokens:
- atokentosecuredata # it can be token gave by slack for example or own tokens which must be complicated
#host: http://localhost:8080 # (optional) this is only to be able to give default icons. this is totally unnecessary in a cloud environment
log_level: ~ # info when it's nil, other values can be: off, all, warning, severe, error, debug and info
config:
  slack_income_url: "http://localhost/hooks/975rc3rxyjbs5pz8e4rjn7mm5y"
  gubot_answer_to_the_ultimate_question_of_life_the_universe_and_everything: "42"
services:
# use a local mysql as a storer, you can do the same for postgres and mssql
#  - name: mysql
#    credentials:
#      uri: mysql://root@localhost:3306/mydb